version: '3.9'

networks:
  unmute-net:
    external: true

volumes:
  traefik-cert:

services:
  frontend:
    image: intellipedia/inti-frontend-groq:openai-tts-v2
    environment:
      - NEXT_PUBLIC_IN_DOCKER=true
      - NEXT_PUBLIC_WS_URL=wss://inti.intellipedia.ai/v1/realtime
      - NEXT_PUBLIC_API_BASE=https://inti.intellipedia.ai/api
      - NEXT_PUBLIC_BACKEND_URL=https://inti.intellipedia.ai/api
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`inti.intellipedia.ai`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls=true"
        - "traefik.http.routers.frontend.tls.certresolver=le"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"
        - "traefik.http.routers.frontend.priority=50"
    networks:
      - unmute-net

  backend:
    image: intellipedia/pipecat-groq-backend:openai-tts-fixed-v2
    env_file:
      - .env
    environment:
      - INTI_ALLOW_MOCK_KEYS=${INTI_ALLOW_MOCK_KEYS:-false}
      - INTI_LOG_LEVEL=DEBUG
      - INTI_SAMPLE_RATE=24000
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        parallelism: 1
        order: start-first
      labels:
        - "traefik.enable=true"
        # WebSocket realtime endpoint
        - "traefik.http.routers.backend-realtime.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/v1/realtime`)"
        - "traefik.http.routers.backend-realtime.entrypoints=websecure"
        - "traefik.http.routers.backend-realtime.tls=true"
        - "traefik.http.routers.backend-realtime.tls.certresolver=le"
        - "traefik.http.routers.backend-realtime.priority=300"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        # API endpoints
        - "traefik.http.routers.backend-api.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/api`)"
        - "traefik.http.routers.backend-api.entrypoints=websecure"
        - "traefik.http.routers.backend-api.tls=true"
        - "traefik.http.routers.backend-api.tls.certresolver=le"
        - "traefik.http.routers.backend-api.priority=250"
        - "traefik.http.routers.backend-api.middlewares=backend-stripprefix"
        - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
        - "traefik.http.routers.backend-api.service=backend"
        - "traefik.http.routers.backend-realtime.service=backend"
    networks:
      - unmute-net

