version: '3.9'

networks:
  unmute-net:
    external: true

services:
  traefik:
    image: traefik:v3.3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@intellipedia.ai"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/acme.json:/data/acme.json
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - unmute-net

  frontend:
    image: intellipedia/inti-frontend:v15.11.25
    environment:
      - NEXT_PUBLIC_IN_DOCKER=true
      - NEXT_PUBLIC_WS_URL=wss://inti.intellipedia.ai/v1/realtime
      - NEXT_PUBLIC_API_BASE=https://inti.intellipedia.ai/api
      - NEXT_PUBLIC_BACKEND_URL=https://inti.intellipedia.ai/api
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`inti.intellipedia.ai`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls=true"
        - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"
        - "traefik.http.routers.frontend.priority=50"
    networks:
      - unmute-net

  backend:
    image: intellipedia/inti-pipecat-backend:dev.15
    env_file:
      - .env
    environment:
      - INTI_ALLOW_MOCK_KEYS=${INTI_ALLOW_MOCK_KEYS:-false}
      - INTI_LOG_LEVEL=${INTI_LOG_LEVEL:-INFO}
      - INTI_SAMPLE_RATE=${INTI_SAMPLE_RATE:-48000}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        parallelism: 1
        order: start-first
      labels:
        - "traefik.enable=true"
        # WebSocket realtime endpoint
        - "traefik.http.routers.backend-realtime.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/v1/realtime`)"
        - "traefik.http.routers.backend-realtime.entrypoints=websecure"
        - "traefik.http.routers.backend-realtime.tls=true"
        - "traefik.http.routers.backend-realtime.tls.certresolver=letsencrypt"
        - "traefik.http.routers.backend-realtime.priority=300"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        # API endpoints
        - "traefik.http.routers.backend-api.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/api`)"
        - "traefik.http.routers.backend-api.entrypoints=websecure"
        - "traefik.http.routers.backend-api.tls=true"
        - "traefik.http.routers.backend-api.tls.certresolver=letsencrypt"
        - "traefik.http.routers.backend-api.priority=250"
        - "traefik.http.routers.backend-api.middlewares=backend-stripprefix"
        - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
        - "traefik.http.routers.backend-api.service=backend"
        - "traefik.http.routers.backend-realtime.service=backend"
    networks:
      - unmute-net