version: '3.9'

networks:
  unmute-net:
    external: true

services:
  traefik:
    image: traefik:v3.3.1
    command:
      - "--configFile=/etc/traefik/traefik-static.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/traefik-static.yml:/etc/traefik/traefik-static.yml:ro
      - /root/traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /root/certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        order: stop-first
    networks:
      - unmute-net

  frontend:
    image: intellipedia/inti-frontend:v15.11.25
    environment:
      - NEXT_PUBLIC_IN_DOCKER=true
      - NEXT_PUBLIC_WS_URL=wss://inti.intellipedia.ai/v1/realtime
      - NEXT_PUBLIC_API_BASE=https://inti.intellipedia.ai/api
      - NEXT_PUBLIC_BACKEND_URL=https://inti.intellipedia.ai/api
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`inti.intellipedia.ai`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls=true"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"
        - "traefik.http.routers.frontend.priority=50"
    networks:
      - unmute-net

  backend:
    image: intellipedia/inti-pipecat-backend:dev.15
    env_file:
      - .env
    environment:
      - INTI_ALLOW_MOCK_KEYS=${INTI_ALLOW_MOCK_KEYS:-false}
      - INTI_LOG_LEVEL=${INTI_LOG_LEVEL:-INFO}
      - INTI_SAMPLE_RATE=${INTI_SAMPLE_RATE:-48000}
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://127.0.0.1:8000/health\")'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        parallelism: 1
        order: start-first
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/api/v1/realtime`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.priority=300"
        - "traefik.http.routers.backend.middlewares=pipecat-strip,pipecat-ws"
        - "traefik.http.routers.backend.service=backend"
        - "traefik.http.routers.backend-direct.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/v1/realtime`)"
        - "traefik.http.routers.backend-direct.entrypoints=websecure"
        - "traefik.http.routers.backend-direct.tls=true"
        - "traefik.http.routers.backend-direct.priority=300"
        - "traefik.http.routers.backend-direct.middlewares=pipecat-ws"
        - "traefik.http.routers.backend-direct.service=backend"
        - "traefik.http.routers.backend-health.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/api/v1/health`)"
        - "traefik.http.routers.backend-health.entrypoints=websecure"
        - "traefik.http.routers.backend-health.tls=true"
        - "traefik.http.routers.backend-health.priority=320"
        - "traefik.http.routers.backend-health.middlewares=pipecat-strip,pipecat-health"
        - "traefik.http.routers.backend-health.service=backend"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        - "traefik.http.middlewares.pipecat-strip.stripprefix.prefixes=/api"
        - "traefik.http.middlewares.pipecat-ws.replacepath.path=/ws"
        - "traefik.http.middlewares.pipecat-health.replacepath.path=/health"
    networks:
      - unmute-net
